Java doc improve post post manager
CSC207-UofT/course-project-git-good-207 pull request #108
Opened 2021-11-29 04:08 UTC by sebastianibam002

2021-12-02 02:19 UTC, ericjest requested changes

2021-12-02 02:19 UTC, ericjest commented on src/main/java/use_cases/PostManager.java
> +        // Post[] allPosts = this.databaseManager.getAllPosts();
if we don't need this line of code can we delete it?

2021-12-03 02:19 UTC, yowang20 requested changes

2021-12-03 02:19 UTC, yowang20 commented on src/main/java/entities/Post.java
> +     * @return return the time when it was posted
Return the time Post was created

2021-12-03 02:19 UTC, yowang20 commented on src/main/java/entities/Post.java
> +     * given a Comment object it adds it stores the new
Saves the comment to the Post's list of comments

2021-12-03 02:19 UTC, yowang20 commented on src/main/java/entities/Post.java
> +     * @param comment stores the information about the
the comment to be added to the post

2021-12-03 02:19 UTC, yowang20 commented on src/main/java/entities/Post.java
> +     * given the user that decided to like the post
Adds the given user to the Post's list of liked users.

2021-12-03 02:19 UTC, yowang20 commented on src/main/java/entities/Post.java
> +     * @param user user that gave like to the post
The user that liked the post

2021-12-03 02:19 UTC, yowang20 commented on src/main/java/entities/Post.java
> +     * users that have given like to the Post
All the users that liked the Post

2021-12-03 13:08 UTC, ericjest approved these changes

2021-12-05 02:00 UTC, ericjest commented
@sebastianibam002 can you resolve the conflicts in your terminal?

2021-12-05 02:06 UTC, sebastianibam002 commented
Let me try

2021-12-05 02:22 UTC, merged